define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color (e.g. gray / grey).
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "kahvatusinine",
antiquewhite: "antiikvalge",
aqua: "rohekassinine",
aquamarine: "akvamariin",
azure: "taevasinine",
beige: "beež",
bisque: "biskviitpruun",
black: "must",
blanchedalmond: "kooritud mandel",
blue: "sinine",
blueviolet: "sinakasvioletne",
brown: "pruun",
burlywood: "puidupruun",
cadetblue: "kadetisinine",
chartreuse: "kollakasroheline",
chocolate: "šokolaad",
coral: "korallpunane",
cornflowerblue: "rukkilillesinine",
cornsilk: "maisikollane",
crimson: "erepunane",
cyan: "tsüaan",
darkblue: "tumesinine",
darkcyan: "tumetsüaan",
darkgoldenrod: "tume kuldvitsakollane",
darkgray: "tumehall",
darkgreen: "tumeroheline",
darkgrey: "tumehall", // same as darkgray
darkkhaki: "tume khaki",
darkmagenta: "tume magenta",
darkolivegreen: "tume oliiviroheline",
darkorange: "tumeoranž",
darkorchid: "tume orhidee",
darkred: "tumepunane",
darksalmon: "tume lõheroosa",
darkseagreen: "tume mereroheline",
darkslateblue: "tume lillakassinine",
darkslategray: "tume rohekashall",
darkslategrey: "tume rohekashall", // same as darkslategray
darkturquoise: "tume türkiis",
darkviolet: "tume violetne",
deeppink: "sügavroosa",
deepskyblue: "sügav taevasinine",
dimgray: "tuhmhall",
dimgrey: "tuhmhall", // same as dimgray
dodgerblue: "erksinine",
firebrick: "tellisepunane",
floralwhite: "lillevalge",
forestgreen: "metsaroheline",
fuchsia: "fuksiapunane",
gainsboro: "tumesinine",
ghostwhite: "kummitusevalge",
gold: "kuld",
goldenrod: "kuldvitsakollane",
gray: "hall",
green: "roheline",
greenyellow: "rohekaskollane",
grey: "hall", // same as gray
honeydew: "kollakashallikas",
hotpink: "erkroosa",
indianred: "indiapunane",
indigo: "indigosinine",
ivory: "elevandiluu",
khaki: "khaki",
lavender: "lavendel",
lavenderblush: "õrn lavendel",
lawngreen: "mururoheline",
lemonchiffon: "õrn sidrunikollane",
lightblue: "helesinine",
lightcoral: "hele korallpunane",
lightcyan: "hele tsüaan",
lightgoldenrodyellow: "hele kuldvitsakollane",
lightgray: "helehall",
lightgreen: "heleroheline",
lightgrey: "helehall", // same as lightgray
lightpink: "heleroosa",
lightsalmon: "hele lõheroosa",
lightseagreen: "hele mereroheline",
lightskyblue: "hele taevasinine",
lightslategray: "hele suitsuhall",
lightslategrey: "hele suitsuhall", // same as lightslategray
lightsteelblue: "hele terassinine",
lightyellow: "helekollane",
lime: "laim",
limegreen: "laimiroheline",
linen: "linavalge",
magenta: "magenta",
maroon: "kastanpruun",
mediumaquamarine: "keskmine akvamariin",
mediumblue: "keskmine sinine",
mediumorchid: "keskmine orhideeroosa",
mediumpurple: "keskmine lilla",
mediumseagreen: "keskmine mereroheline",
mediumslateblue: "keskmine lillakassinine",
mediumspringgreen: "keskmine kevadroheline",
mediumturquoise: "keskmine türkiissinine",
mediumvioletred: "keskmine roosakaspunane",
midnightblue: "öösinine",
mintcream: "piparmündikreemikas",
mistyrose: "udune roos",
moccasin: "mokassiinipruun",
navajowhite: "navajobeež",
navy: "mereväesinine",
oldlace: "vana pits",
olive: "oliivroheline",
olivedrab: "tuhm oliivroheline",
orange: "oranž",
orangered: "oranžikaspunane",
orchid: "orhidee",
palegoldenrod: "kahvatu kuldvitsakollane",
palegreen: "kahvaturoheline",
paleturquoise: "kahvatu türkiissinine",
palevioletred: "kahvatu lillakaspunane",
papayawhip: "papaiavaht",
peachpuff: "virsikuroosa",
peru: "peruu",
pink: "roosa",
plum: "ploomililla",
powderblue: "tuhmsinine",
purple: "lilla",
red: "punane",
rosybrown: "roosakaspruun",
royalblue: "sügavsinine",
saddlebrown: "sadulapruun",
salmon: "lõheroosa",
sandybrown: "liivapruun",
seagreen: "mereroheline",
seashell: "merikarp",
sienna: "sienna",
silver: "hõbedane",
skyblue: "taevasinine",
slateblue: "lillakassinine",
slategray: "suitsuhall",
slategrey: "suitsuhall", // same as slategray
snow: "lumi",
springgreen: "kevadroheline",
steelblue: "terassinine",
tan: "kollakaspruun",
teal: "rohekassinine",
thistle: "ohakaroosa",
tomato: "tomat",
transparent: "läbipaistev",
turquoise: "türkiissinine",
violet: "violetne",
wheat: "nisukollane",
white: "valge",
whitesmoke: "suitsuvalge",
yellow: "kollane",
yellowgreen: "kollakasroheline"
})
//end v1.x content

);
