define(
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color (e.g. gray / grey).
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "अलाइस नीला",
antiquewhite: "विरल सफेद",
aqua: "जलीय",
aquamarine: "जलसमुद्री",
azure: "आसमानी",
beige: "गहरा पीला",
bisque: "गाढ़ा भूरा",
black: "काला",
blanchedalmond: "हल्का बादामी",
blue: "नीला",
blueviolet: "नीला-बैंगनी",
brown: "भूरा",
burlywood: "बर्लीवुड",
cadetblue: "कैडेट नीला",
chartreuse: "पीला-हरा",
chocolate: "चाकलेटी",
coral: "प्रवाल",
cornflowerblue: "कार्नफ्लोर नीला",
cornsilk: "कॉर्नसिल्क",
crimson: "गहरा लाल",
cyan: "स्यान",
darkblue: "गहरा नीला",
darkcyan: "गहरा स्यान",
darkgoldenrod: "गहरा गोल्डनरॉड",
darkgray: "गहरा ग्रे",
darkgreen: "गहरा हरा",
darkgrey: "गहरा ग्रे", // same as darkgray
darkkhaki: "गहरा खाकी",
darkmagenta: "गहरा लाल-गुलाबी",
darkolivegreen: "गहरा जैतूनी हरा",
darkorange: "गहरा नारंगी",
darkorchid: "गहरा ऑर्चिड",
darkred: "गहरा लाल",
darksalmon: "गहरा गेरुआ",
darkseagreen: "गहरा समुद्री हरा",
darkslateblue: "गहरा स्लेटी नीला",
darkslategray: "गहरा स्लेटी ग्रे",
darkslategrey: "गहरा स्लेटी ग्रे", // same as darkslategray
darkturquoise: "गहरा फीरोज़ी",
darkviolet: "गहरा बैंगनी",
deeppink: "गहरा गुलाबी",
deepskyblue: "गहरा आसमानी नीला",
dimgray: "धुंधला ग्रे",
dimgrey: "धुंधला ग्रे", // same as dimgray
dodgerblue: "पर्चा नीला",
firebrick: "अग्नि ईंट",
floralwhite: "फुलवा सफेद",
forestgreen: "जंगली हरा",
fuchsia: "फुशिया",
gainsboro: "गेन्सबोरो",
ghostwhite: "भुतिया सफेद",
gold: "सोना",
goldenrod: "गोल्डनरॉड",
gray: "ग्रे",
green: "हरा",
greenyellow: "हरा-पीला",
grey: "ग्रे", // same as gray
honeydew: "खजूरी",
hotpink: "गहरा गुलाबी",
indianred: "भारतीय लाल",
indigo: "नील",
ivory: "हाथीदंत",
khaki: "खाकी",
lavender: "बैंगनी-नीला",
lavenderblush: "बैंगनी-नीली लालिमा",
lawngreen: "दूर्वा हरा",
lemonchiffon: "पीला शिफॉन",
lightblue: "हल्का नीला",
lightcoral: "हल्का प्रवाल",
lightcyan: "हल्का स्यान",
lightgoldenrodyellow: "हल्का गोल्डनरॉड पीला",
lightgray: "हल्का ग्रे",
lightgreen: "हल्का हरा",
lightgrey: "हल्का ग्रे", // same as lightgray
lightpink: "हल्का गुलाबी",
lightsalmon: "हल्का गेरुआ",
lightseagreen: "हल्का समुद्री हरा",
lightskyblue: "हल्का आसमानी नीला",
lightslategray: "हल्का स्लेटी ग्रे",
lightslategrey: "हल्का स्लेटी ग्रे", // same as lightslategray
lightsteelblue: "हल्का स्टील नीला",
lightyellow: "हल्का पीला",
lime: "चूना",
limegreen: "चूना हरा",
linen: "लिनेन",
magenta: "लाल-गुलाबी",
maroon: "लाल-भूरा",
mediumaquamarine: "मध्यम जलसमुद्री",
mediumblue: "मध्यम नीला",
mediumorchid: "मध्यम ऑर्चिड",
mediumpurple: "मध्यम जामुनी",
mediumseagreen: "मध्यम समुद्री हरा",
mediumslateblue: "मध्यम स्लेटी नीला",
mediumspringgreen: "मध्यम स्प्रिंग हरा",
mediumturquoise: "मध्यम फीरोज़ी",
mediumvioletred: "मध्यम बैंगनी-लाल",
midnightblue: "अतिगहरा नीला",
mintcream: "मिंट क्रीम",
mistyrose: "धुंधला गुलाबी",
moccasin: "मोकेसिन",
navajowhite: "नेवाजो सफेद",
navy: "समूद्री",
oldlace: "पुराना फीता",
olive: "जैतूनी",
olivedrab: "जैतूनी मैला",
orange: "नारंगी",
orangered: "नारंगी लाल",
orchid: "ऑर्चिड",
palegoldenrod: "फीका गोल्डनरॉड",
palegreen: "फीका हरा",
paleturquoise: "फीका फीरोज़ी",
palevioletred: "फीका बैंगनी-लाल",
papayawhip: "पपाया व्हिप",
peachpuff: "आडू पफ",
peru: "पेरू",
pink: "गुलाबी",
plum: "आलुबुखारा",
powderblue: "चूर्ण नीला",
purple: "जामुनी",
red: "लाल",
rosybrown: "गुलाबी भूरा",
royalblue: "राजसी नीला",
saddlebrown: "काठी भूरा",
salmon: "गेरूआ",
sandybrown: "रेतीला भूरा",
seagreen: "समुद्री हरा",
seashell: "समुद्री-सीपी",
sienna: "मटमैला",
silver: "चांदी",
skyblue: "आसमानी नीला",
slateblue: "स्लेटी नीला",
slategray: "स्लेटी ग्रे",
slategrey: "स्लेटी ग्रे", // same as slategray
snow: "हिम",
springgreen: "स्प्रिंग हरा",
steelblue: "स्टील नीला",
tan: "पीला भूरा",
teal: "बत्तखी",
thistle: "भटकैय्या",
tomato: "टमाटरी",
transparent: "पारदर्शी",
turquoise: "फीरोज़ी",
violet: "बैंगनी",
wheat: "गेहूंआ",
white: "सफेद",
whitesmoke: "सफेद धुंधला",
yellow: "पीला",
yellowgreen: "पीला हरा"
})
);
