define(
//begin v1.x content
({
// local representation of all CSS3 named colors, companion to dojo.colors.  To be used where descriptive information
// is required for each color, such as a palette widget, and not for specifying color programatically.

//Note: due to the SVG 1.0 spec additions, some of these are alternate spellings for the same color (e.g. gray / grey).
//TODO: should we be using unique rgb values as keys instead and avoid these duplicates, or rely on the caller to do the reverse mapping?
aliceblue: "xanh lá",
antiquewhite: "màu trắng cổ",
aqua: "màu ngọc xanh biển",
aquamarine: "màu ngọc xanh biển",
azure: "màu xanh da trời",
beige: "màu be",
bisque: "sứ không tráng men",
black: "màu đen",
blanchedalmond: "hạt hạnh nhân trần",
blue: "xanh lam",
blueviolet: "xanh tím",
brown: "nâu",
burlywood: "màu cát cháy",
cadetblue: "màu xanh cadet",
chartreuse: "màu lục nhạt",
chocolate: "sôcôla",
coral: "đỏ san hô",
cornflowerblue: "xanh hoa ngô",
cornsilk: "râu ngô",
crimson: "đỏ thẫm",
cyan: "màu lục lam",
darkblue: "màu xanh sẫm",
darkcyan: "màu lục lam sẫm",
darkgoldenrod: "màu vàng ánh kim sẫm",
darkgray: "xám đậm",
darkgreen: "màu xanh lục sẫm",
darkgrey: "xám đậm", // same as darkgray
darkkhaki: "kaki sẫm",
darkmagenta: "đỏ tươi đậm",
darkolivegreen: "xanh ô liu sẫm",
darkorange: "màu cam đậm",
darkorchid: "phong lan sẫm màu",
darkred: "đỏ sẫm",
darksalmon: "màu hồng da cam đậm",
darkseagreen: "xanh biển đậm",
darkslateblue: "màu xanh đá đậm",
darkslategray: "xám đá đậm",
darkslategrey: "xám đá đậm", // same as darkslategray
darkturquoise: "màu ngọc lam sẫm",
darkviolet: "màu tím đậm",
deeppink: "màu hồng đậm",
deepskyblue: "màu xanh da trời sẫm",
dimgray: "xám mờ",
dimgrey: "xám mờ", // same as dimgray
dodgerblue: "xanh lơ lam",
firebrick: "màu đỏ gạch",
floralwhite: "màu trắng hoa",
forestgreen: "màu xanh lục đậm",
fuchsia: "màu hoa vân anh",
gainsboro: "màu xám sáng",
ghostwhite: "màu trắng toát",
gold: "màu vàng",
goldenrod: "màu vàng ánh kim",
gray: "màu xám",
green: "màu xanh lá cây",
greenyellow: "màu vàng-xanh",
grey: "màu xám", // same as gray
honeydew: "màu trắng hơi xanh lục",
hotpink: "màu hồng nóng",
indianred: "màu đỏ Ấn độ",
indigo: "màu chàm",
ivory: "màu ngà",
khaki: "màu kaki",
lavender: "màu hoa oải hương",
lavenderblush: "màu trắng hơi hồng",
lawngreen: "màu xanh lục nhạt chói lọi",
lemonchiffon: "màu vàng nhợt nhạt",
lightblue: "màu xanh da trời nhạt",
lightcoral: "màu đỏ nhạt",
lightcyan: "màu lục lam nhạt",
lightgoldenrodyellow: "màu vàng ánh kim nhạt",
lightgray: "xám nhạt",
lightgreen: "màu xanh lục nhạt",
lightgrey: "xám nhạt", // same as lightgray
lightpink: "màu hồng nhạt",
lightsalmon: "màu đỏ cam sáng",
lightseagreen: "màu xanh lơ",
lightskyblue: "màu xanh da trời nhạt",
lightslategray: "xám đá nhạt",
lightslategrey: "xám đá nhạt", // same as lightslategray
lightsteelblue: "màu xanh thép nhạt",
lightyellow: "màu vàng nhạt",
lime: "màu vàng chanh",
limegreen: "màu xanh chanh",
linen: "màu vải bố",
magenta: "màu đỏ tươi",
maroon: "màu nâu sẫm",
mediumaquamarine: "màu ngọc xanh biển vừa",
mediumblue: "màu xanh nước biển vừa",
mediumorchid: "màu hoa phong lan vừa",
mediumpurple: "màu tím vừa",
mediumseagreen: "màu xanh biển vừa",
mediumslateblue: "màu xanh đá vừa",
mediumspringgreen: "màu xanh lục lơ chói",
mediumturquoise: "màu xanh lơ rực rỡ",
mediumvioletred: "màu hồng sẫm mạnh",
midnightblue: "màu xanh đen thẫm",
mintcream: "màu kem xanh bạc hà",
mistyrose: "màu trắng hơi đỏ tươi",
moccasin: "màu rắn hổ mang",
navajowhite: "màu cam nâu nhạt",
navy: "trắng hơi cam nâu",
oldlace: "màu trắng hơi cam",
olive: "màu xanh ôliu",
olivedrab: "màu vàng xanh lục mạnh",
orange: "màu cam",
orangered: "màu đỏ cam",
orchid: "màu hồng sẫm sáng",
palegoldenrod: "màu vàng ánh kim nhợt nhạt",
palegreen: "màu xanh lục nhợt nhạt",
paleturquoise: "màu ngọc lam nhợt nhạt",
palevioletred: "màu hồng sẫm nhợt nhạt",
papayawhip: "màu trắng hơi cam nâu",
peachpuff: "màu cam nâu nhợt nhạt",
peru: "màu cam (nâu) chói",
pink: "màu hồng",
plum: "màu mận chín",
powderblue: "màu xanh lơ nhợt nhạt",
purple: "màu tím đỏ",
red: "màu đỏ",
rosybrown: "màu đỏ nhạt",
royalblue: "màu xanh lam chói lọi",
saddlebrown: "màu cam chín đậm",
salmon: "màu hồng da cam",
sandybrown: "màu cam (nâu) sáng",
seagreen: "màu xanh biển",
seashell: "màu trắng hơi cam",
sienna: "màu hung đỏ",
silver: "màu bạc",
skyblue: "màu xanh da trời",
slateblue: "màu xanh đá",
slategray: "xám đá",
slategrey: "xám đá", // same as slategray
snow: "màu trắng tuyết",
springgreen: "màu xanh bắp cải non",
steelblue: "màu xanh thép",
tan: "màu nâu vàng nhạt",
teal: "màu xanh mòng két",
thistle: "màu hoa cây kế",
tomato: "màu đỏ cà chua",
transparent: "màu trong suốt",
turquoise: "màu ngọc lam",
violet: "màu tím",
wheat: "màu cam-nâu rất nhợt nhạt",
white: "màu trắng",
whitesmoke: "màu khói trắng",
yellow: "màu vàng",
yellowgreen: "màu xanh vàng"
})
//end v1.x content

);
